apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-routing
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: iot-application
                port:
                  number: 8888
